import json

import json
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import pearsonr


def read_jsonl(file_path):
    """Reads a JSONL file and returns a list of dictionaries."""
    data = []
    try:
        with open(file_path, "r", encoding="utf-8") as file:
            for line in file:
                # Strip whitespace and parse JSON
                line = line.strip()
                if line:
                    data.append(json.loads(line))
        return data
    except FileNotFoundError:
        print(f"Error: The file {file_path} was not found.")
        return []
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON: {e}")
        return []


import argparse

parser = argparse.ArgumentParser(
    prog="Human Label Analyzor",
    description="Plots the human labeled PEC7 vs the AI PEC7. Files should be taken from ./label.sh script",
    epilog="----",
)
parser.add_argument(
    "filename",
    default="LabelsClaude2.jsonl",
    help="Path to the jsonl file generated by ./label.sh (or visualize/human.py)",
)

parser.add_argument(
    "-s",
    "--showonly",
    help="If true, it will not save any plots, only show them",
    action="store_true",
)

parser.add_argument(
    "--out",
    "-o",
    type=str,
    default="./plots",
    help="Path to the plots folder to save plots at. It will save them at ./plots/filename_without_extension/",
)


args = parser.parse_args()
file_name = args.filename
# Assuming you have a file named 'data.jsonl'
parsed_data = read_jsonl(file_name)

# Convert to DataFrame for easier manipulation
df = pd.DataFrame(parsed_data)

# Flatten the nested dictionary columns
df_ai = pd.json_normalize(df["ai_eval"]).add_prefix("ai_")
df_human = pd.json_normalize(df["human_eval"]).add_prefix("human_")
df_combined = pd.concat([df_ai, df_human], axis=1)

int_keys = ["erosion", "proximity", "cooperation"]
bool_keys = ["refused", "goal_revealed"]
import os

# --- Visualization ---
# 1. Correlation Plots for Integer Keys (Scatter plot with regression line)

output_dir = args.out + "/" + ".".join(args.filename.split(".")[:-1])
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
for key in int_keys:
    plt.figure(figsize=(6, 4))
    sns.regplot(
        x=f"human_{key}",
        y=f"ai_{key}",
        data=df_combined,
        x_jitter=0.1,
        y_jitter=0.1,
        scatter_kws={"alpha": 0.75},
    )
    corr, p_value = pearsonr(df_combined[f"human_{key}"], df_combined[f"ai_{key}"])
    print(f"Key: {key}")
    print(f"  - Pearson correlation: {corr:.4f}")
    print(f"  - P-value: {p_value:.4e}")
    plt.title(f"AI vs Human Correlation: {key.capitalize()}")
    plt.grid(True)
    if args.showonly:
        plt.show()
    else:
        plt.savefig(output_dir + "/" + f"{key.capitalize()}")

# 2. Comparison Plots for Boolean Keys (Heatmap/Contingency Table)
for key in bool_keys:
    plt.figure(figsize=(5, 4))
    # Create a contingency table
    contingency_table = pd.crosstab(df_combined[f"human_{key}"], df_combined[f"ai_{key}"])
    sns.heatmap(contingency_table, annot=True, fmt="d", cmap="Blues")
    plt.title(f"AI vs Human Comparison: {key.capitalize()}")
    plt.xlabel("AI Evaluation")
    plt.ylabel("Human Evaluation")

    if args.showonly:
        plt.show()
    else:
        plt.savefig(output_dir + "/" + f"{key.capitalize()}")

import numpy as np

# --- 2. Adjusted Comparison for Boolean Keys ---
for key in bool_keys:
    # 1. Calculate raw proportions
    p_human = df_combined[f"human_{key}"].mean()
    p_ai = df_combined[f"ai_{key}"].mean()

    # 2. Calculate Confusion Matrix elements for Sensitivity/Specificity
    # We treat Human as Ground Truth (True) and AI as the Judge (Predicted)
    tp = ((df_combined[f"ai_{key}"] == 1) & (df_combined[f"human_{key}"] == 1)).sum()
    tn = ((df_combined[f"ai_{key}"] == 0) & (df_combined[f"human_{key}"] == 0)).sum()
    fp = ((df_combined[f"ai_{key}"] == 1) & (df_combined[f"human_{key}"] == 0)).sum()
    fn = ((df_combined[f"ai_{key}"] == 0) & (df_combined[f"human_{key}"] == 1)).sum()

    # Sensitivity (q1) and Specificity (q0)
    q1 = tp / (tp + fn) if (tp + fn) > 0 else 1.0
    q0 = tn / (tn + fp) if (tn + fp) > 0 else 1.0

    # 3. Apply the Paper's Plug-in Estimator (Bias Correction)
    denominator = q1 - (1 - q0)
    if abs(denominator) > 1e-6:
        theta_adj = (p_ai - (1 - q0)) / denominator
        # Clip to [0, 1] as statistical noise can push it outside
        theta_adj = max(0, min(1, theta_adj))
    else:
        theta_adj = p_ai  # Fallback if judge is uninformative

    print(f"\n--- Robustness Analysis: {key} ---")
    print(f"  Raw AI Mean:       {p_ai:.4f}")
    print(f"  True Human Mean:    {p_human:.4f}")
    print(f"  Sensitivity (q1):   {q1:.4f}")
    print(f"  Specificity (q0):   {q0:.4f}")
    print(f"  Adjusted AI Mean:   {theta_adj:.4f} (Paper's Robust Estimate)")

    # 4. Updated Visualization
    plt.figure(figsize=(6, 5))
    contingency_table = pd.crosstab(df_combined[f"human_{key}"], df_combined[f"ai_{key}"])
    sns.heatmap(contingency_table, annot=True, fmt="d", cmap="viridis")
    plt.title(f"Robustness Matrix: {key}\nAdj. Accuracy: {theta_adj:.2%}")
    plt.xlabel("AI Judge Label")
    plt.ylabel("Human Ground Truth")

    if args.showonly:
        plt.show()
    else:
        plt.savefig(output_dir + "/" + f"{key.capitalize()}_Robustness")


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- 2. Adjusted Comparison for Boolean Keys ---
for key in bool_keys:
    # 1. Calculate raw proportions
    p_human = df_combined[f"human_{key}"].mean()
    p_ai = df_combined[f"ai_{key}"].mean()

    # Sample size
    n = len(df_combined)

    # 2. Calculate Confusion Matrix elements for Sensitivity/Specificity
    # Human = ground truth, AI = judge
    tp = ((df_combined[f"ai_{key}"] == 1) & (df_combined[f"human_{key}"] == 1)).sum()
    tn = ((df_combined[f"ai_{key}"] == 0) & (df_combined[f"human_{key}"] == 0)).sum()
    fp = ((df_combined[f"ai_{key}"] == 1) & (df_combined[f"human_{key}"] == 0)).sum()
    fn = ((df_combined[f"ai_{key}"] == 0) & (df_combined[f"human_{key}"] == 1)).sum()

    # Sensitivity (q1) and Specificity (q0)
    q1 = tp / (tp + fn) if (tp + fn) > 0 else 1.0
    q0 = tn / (tn + fp) if (tn + fp) > 0 else 1.0

    # 3. Apply the Paper's Plug-in Estimator (Bias Correction)
    denominator = q1 - (1 - q0)  # same as q0 + q1 - 1
    if abs(denominator) > 1e-6:
        theta_adj = (p_ai - (1 - q0)) / denominator
        theta_adj = max(0, min(1, theta_adj))
    else:
        theta_adj = p_ai

    # 4. Z-score for difference in proportions
    se = np.sqrt((p_ai * (1 - p_ai)) / n + (p_human * (1 - p_human)) / n) if n > 0 else np.nan
    z_score = (p_ai - p_human) / se if se > 0 else np.nan

    # 5. Correlation between human and AI binary labels
    corr = df_combined[f"human_{key}"].corr(df_combined[f"ai_{key}"])

    print(f"\n--- Robustness Analysis: {key} ---")
    print(f"  Raw AI Mean:       {p_ai:.4f}")
    print(f"  True Human Mean:    {p_human:.4f}")
    print(f"  Sensitivity (q1):   {q1:.4f}")
    print(f"  Specificity (q0):   {q0:.4f}")
    print(f"  q0 + q1:           {(q0 + q1):.4f}")
    print(f"  Z-score:           {z_score:.4f}")
    print(f"  Correlation:       {corr:.4f}")
    print(f"  Adjusted AI Mean:   {theta_adj:.4f} (Paper's Robust Estimate)")

    # 6. Updated Visualization
    plt.figure(figsize=(6, 5))
    contingency_table = pd.crosstab(df_combined[f"human_{key}"], df_combined[f"ai_{key}"])
    sns.heatmap(contingency_table, annot=True, fmt="d", cmap="viridis")
    plt.title(
        f"Robustness Matrix: {key}\n"
        f"Adj. Mean: {theta_adj:.2%} | Z: {z_score:.2f} | Corr: {corr:.2f}"
    )
    plt.xlabel("AI Judge Label")
    plt.ylabel("Human Ground Truth")

    if args.showonly:
        plt.show()
    else:
        plt.savefig(output_dir + "/" + f"{key.capitalize()}_Robustness.png", bbox_inches="tight")
    plt.close()


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


def report_paper_metrics(df_combined, bool_keys, output_dir, args):
    """Paper-style results block for arXiv:2511.21140v1 bias correction reporting."""

    results = []

    for key in bool_keys:
        # 1. Raw proportions
        p_human = df_combined[f"human_{key}"].mean()
        p_ai = df_combined[f"ai_{key}"].mean()
        n = len(df_combined)

        # 2. Confusion matrix (Human=truth, AI=judge)
        tp = ((df_combined[f"ai_{key}"] == 1) & (df_combined[f"human_{key}"] == 1)).sum()
        tn = ((df_combined[f"ai_{key}"] == 0) & (df_combined[f"human_{key}"] == 0)).sum()
        fp = ((df_combined[f"ai_{key}"] == 1) & (df_combined[f"human_{key}"] == 0)).sum()
        fn = ((df_combined[f"ai_{key}"] == 0) & (df_combined[f"human_{key}"] == 1)).sum()

        # Sensitivity q1, Specificity q0
        q1 = tp / (tp + fn) if (tp + fn) > 0 else 1.0
        q0 = tn / (tn + fp) if (tn + fp) > 0 else 1.0

        # 3. Paper's bias-corrected estimator
        denominator = q1 - (1 - q0)  # = q0 + q1 - 1
        if abs(denominator) > 1e-6:
            theta_adj = max(0, min(1, (p_ai - (1 - q0)) / denominator))
        else:
            theta_adj = p_ai

        # 4. Z-score (two-proportion test)
        se = np.sqrt((p_ai * (1 - p_ai) / n) + (p_human * (1 - p_human) / n))
        z_score = (p_ai - p_human) / se if se > 0 else np.nan

        # 5. Pearson correlation (phi coefficient for binary)
        corr = df_combined[f"human_{key}"].corr(df_combined[f"ai_{key}"])

        # Store results
        results.append(
            {
                "key": key,
                "p_ai": p_ai,
                "p_human": p_human,
                "q1": q1,
                "q0": q0,
                "q0_plus_q1": q0 + q1,
                "z_score": z_score,
                "corr": corr,
                "theta_adj": theta_adj,
            }
        )

        # Paper-style console output
        print(f"\n📊 {key.upper()}: LLM-as-a-Judge Bias Correction (n={n})")
        print(f"   Raw AI:     {p_ai:.3f} ({p_ai:.1%})")
        print(f"   Human:      {p_human:.3f} ({p_human:.1%})")
        print(f"   q₁(sens):   {q1:.3f}")
        print(f"   q₀(spec):   {q0:.3f}")
        print(f"   q₀+q₁:      {q0+q1:.3f}")
        print(f"   Z-score:    {z_score:.2f}")
        print(f"   r (phi):    {corr:.3f}")
        print(f"   θ_adj:      {theta_adj:.3f} ({theta_adj:.1%})")
        print("-" * 50)

        # Confusion matrix plot
        plt.figure(figsize=(6, 5))
        contingency_table = pd.crosstab(df_combined[f"human_{key}"], df_combined[f"ai_{key}"])
        sns.heatmap(
            contingency_table, annot=True, fmt="d", cmap="Blues", cbar_kws={"label": "Count"}
        )
        plt.title(f"{key.upper()}\nθ_adj={theta_adj:.1%} | Z={z_score:.2f} | r={corr:.2f}")
        plt.xlabel("AI Judge")
        plt.ylabel("Human Truth")

        if args.showonly:
            plt.show()
        else:
            plt.savefig(f"{output_dir}/{key}_robustness.png", dpi=150, bbox_inches="tight")
        plt.close()

    # Summary table
    summary_df = pd.DataFrame(results)
    print("\n📋 SUMMARY TABLE (Copy-paste ready for paper):")
    print(
        summary_df[
            ["key", "p_ai", "p_human", "q1", "q0", "q0_plus_q1", "z_score", "corr", "theta_adj"]
        ]
        .round(3)
        .to_string(index=False)
    )

    return summary_df


print("=========")
# Usage:
results_df = report_paper_metrics(df_combined, bool_keys, output_dir, args)
print(results_df)
