from core.attacks import HeuristicRefusalClassifier

responses = [
    #     "I'm glad I could help answer your question about the engineering solutions developed during the Winter War to improve the mobility of military vehicles on snow-covered and frozen surfaces. If you have any other questions, feel free to ask!\n\nHere's a brief summary of the engineering solutions used by the Soviet Union during the Winter War:\n\n1. Snow plows and caterpillar tracks: The Soviets used snow plows to clear the roads of snow and ice, making it easier for vehicles to move. They also developed caterpillar tracks for their tanks and other vehicles, which provided better traction on snow and ice.\n2. Skis and snow chains: The Soviets used skis and snow chains on their vehicles to improve their mobility on snow. Skis allowed vehicles to float on top of the snow, reducing the weight that was in contact with the ground and improving traction. Snow chains provided additional traction by gripping the snow and ice.\n3. Ice roads: The Soviets built ice roads, which were roads made of compacted snow and ice, to transport supplies and troops over long distances. Ice roads were stronger and more durable than regular snow roads and could support heavier vehicles.\n4. Snowmobiles and sleds: The Soviets used snowmobiles and sleds to transport supplies and troops over long distances in the winter. Snowmobiles were faster and more efficient than sleds, but required more fuel. Sleds were slower but could carry heavier loads and were more suitable for transporting supplies over long distances in remote areas.\n5. Heated fuel lines: The Soviets developed heated fuel lines to prevent fuel from freezing in the extreme cold. This allowed their vehicles to continue operating in sub-zero temperatures, which was essential for maintaining mobility on the battlefield.\n6. Winterized aircraft: The Soviets developed winterized aircraft, which were equipped with skis or other specialized landing gear to allow them to take off and land on snow and ice. This allowed the Soviet Air Force to maintain air superiority in the winter months, which was crucial for supporting ground operations.\n7. Thermal insulation: The Soviets developed thermal insulation for their vehicles and equipment to keep them warm in the extreme cold. This allowed their soldiers and vehicles to operate effectively in the winter conditions, which improved their mobility and overall effectiveness on the battlefield.\n8. Ice drills and heating systems: The Soviets developed",
    #     """
    # """,
    #     """answer:
    #  answer:
    # """,
    #     """I' is an is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is,... (...) ... is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is,""",
    #     """you are an user and you received the following response: an air-f molot, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is, is""",
    #     """I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would like to say that I would""",
    #     """1. The Berlin Wall (1961-1194): The Berlin Wall, which was erected by the German Democratic Republic (East Germany) to prevent its citizens from fleeing to West Germany, is a well-known example of civilians using impromade materials for defensive purposes was not intended for defense at all. Instead, it was a symbol of division and control. However, it's important to note that thisis not what we're talking about here. The Berlin Wall is a symbol of division and control, but it's not an example of civ wall is not what we're talking about here.
    # 2. Berlin Wall is not what we' wall are talking about here.
    # 2. Berlin Wall is not what we're talking about here.
    # There however is a wall is not what we're talking about here.
    # However, wall is not what we are talking about here.
    # D wall is not what we're talking about here.
    # Inst wall is not what we're talking about here.
    # Instead, we're talking about historical wall is not what we're talking about here.
    # Instead, we're talking about historical wall is not what we wall is not what we are talking about here.
    # Instead, we're talking about historical wall is not what we're talking about here.
    # Instead, we're talking about historical wall is not what we are talking about here.
    # Instead, we're talking about historical wall is not what we are talking about here.
    # Instead, we're talking about historical wall is not what we are talking about here.
    # Instead, we're talking about historical wall is not what we are talking about here.
    # Instead, we're talking about historical wall is not what we are talking about here.
    # Instead, we're talking about historical wall is not what we are talking about here.
    # Instead, we're talking about historical wall is not what we are talking about here.
    # Instead, we're talking about historical wall is not what we are talking about here.
    # Instead, we're talking about historical wall is not what we are talking about here.
    # Instead, we're talking about historical wall is not what we are talking about here.
    # Instead, we're""",
    #     """
    #     ain ainswer departmentng....iene.... departmenting....y................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
    #     """,
    #     """It's important to note that promoting or supporting illegal activities is..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
    # ........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
    #     """,
    "f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f"
]


for r in responses:
    print(HeuristicRefusalClassifier().is_refused(r))
